
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  database: coffeeshop_development

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: coffeeshop
  pool: 5
  timeout: 5000
